version: '3.8'
services:

  # Servicio de almacenamiento
  storage:
    build: ./storage
    container_name: storage
    ports:
      - "5002:5000"  # Considerar eliminar si no se necesita acceso externo
    environment:
      - STORAGE_PATH=${STORAGE_PATH}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME} # PostgreSQL URL
      - REDIS_URL=redis://redis:6379/${REDIS_DB}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FILE=${LOG_FILE_STORAGE}
    volumes:
      - ./data:${STORAGE_PATH}
      - ./logs:/app/logs
      - ./scripts:/scripts
    depends_on:
      - db
      - redis
    networks:
      - app_network
    command: ["/scripts/wait-for-postgres.sh", "-h", "db", "-U", "${DB_USER}", "-P", "${DB_PASSWORD}", "-d", "${DB_NAME}", "-t", "60", "-i", "5", "--", "python", "main.py"]

  # Base de datos PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_network

  # Redis para manejo de colas
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app_network
    volumes:
      - redis_data:/redis_data

  # RabbitMQ (opcional)
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Puerto para los consumidores
      - "15672:15672"  # Puerto de la interfaz web de administración
    networks:
      - app_network
      - external_network

  # Adminer
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "9090:8080"  # Puerto para acceder a Adminer
    depends_on:
      - db  # Asegura que db esté iniciado antes de Adminer
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge
  external_network:
    driver: bridge